spring:
  flyway:
    user: andrey
    password: pass
    schemas: carwash
    url: jdbc:postgresql://localhost:5400/carwash
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    username: andrey
    password: pass
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5400/carwash
jwt:
  secret-key:
    access-token: acckeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeey
    refresh-token: refkeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeey
  expiration-time:
    access-token: 30
    refresh-token: 7
