spring:
  flyway:
    user: andrey
    password: pass
    schemas: database1
    url: jdbc:postgresql://localhost:5400/database1
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    username: andrey
    password: pass
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5400/database1
  security:
    user:
      name: andrey
      password: andrey
      roles: admin